### ISSUE TITLE
UNVR does not work when using ipvlan driver

### ISSUE THREAD

**Issue by ultrapravyj** [markdegrootnl/unifi-protect-arm64#30]
I decided to use the ipvlan driver to run the container in a separate vlan. To do this, I made a compos file with the following content:

```
version: '3.8'
services:
  unifi-protect:
    image: markdegroot/unifi-protect-arm64
    container_name: unifi-protect
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /opt/unifi_protect/srv:/srv
      - /mnt/1/unifi_protect/data:/data
      - /opt/unifi_protect/persistent:/persistent
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      unifi_ipvlan:
        ipv4_address: 10.1.11.3
    restart:unless-stopped
/networks:
  unifi_ipvlan:
    driver: ipvlan
    driver_opts:
      parent: eth0.11 
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.1.11.0/24
          gateway: 10.1.11.1
```

And it starts and the address is available on vlan 11, but the web interface does not start.

This is what I see in the most running container
![image](https://github.com/markdegrootnl/unifi-protect-arm64/assets/82925423/9cb23087-bbe6-4b3a-ba65-d89d2b8b8b4a)

Does anyone have any idea how to fix this?
